### ISSUE TITLE
http request monitoring

### ISSUE THREAD

**Issue by fghorbel** [MonsantoCo/cf-metrics#10]
Hi,

Does cf-metrics has metrics about http request statistics? such as, failed requests, response time, ...

Fadel

Thanks,

**Comment by mjseid** [comment]
Hello, 
     we only use this project for monitoring the CF platform itself (from an operator's perspective), so I don't enable http or container metrics on the firehose nozzle in this project when we run it in-house.

The firehose nozzle we use for this (https://github.com/MonsantoCo/influxdb-firehose-nozzle) is capable of capturing the http metrics and container metrics, but we actually run a separate dedicated nozzle and influxdb instance specifically for application monitoring.  Mainly b/c the uri tag of the http metric is un-bounded, which can lead to high series cardinality in the database.  

The stats available as http metric are detailed here in the protocol definition:
https://github.com/cloudfoundry/dropsonde-protocol/blob/master/events/http.proto

**Comment by mjseid** [comment]
Guessing you got what you need.  Closing for now, feel free to reopen if you have additional questions

**Comment by fghorbel** [comment]
Thank you for your response:)
