### ISSUE TITLE
Filter for diego

### ISSUE THREAD

**Issue by Rohitverma47** [MonsantoCo/cf-metrics#9]
can you help me the filters that i would require to see the Diego cells and the applications running on Diego containers

**Comment by mjseid** [comment]
Hey, 
   we've been running this Diego for awhile now but haven't pushed those things (filters, dashboards, etc) to this public repo yet.  I'll try to get an that pushed today to bring this repo up to date with those features.

**Comment by mjseid** [comment]
Now that the I can reach githhub again, I've updated master to include our latest features.  Take a look hopefully that has what you want.

**Comment by Rohitverma47** [comment]
Thank you @mjseid 
One more thing when i am trying to run it on the browser the metrics is not coming, i checked if the influx db is there generating the metrics  but it is working fine.  The error that it is giving is ""error":"missing required parameter \"q\""". Any option if you can help me with. 

Thanks in advance

**Comment by mjseid** [comment]
Looks like you tried to include a screenshot but unfortunately I can't see it.

Are you saying that the grafana dashboards are not working?  The commit I made included an update to grafana 3.1 and some of the dashboards require that newer version.  If you are running on the same docker host you were previously, can you make sure to remove the old docker images using "docker-compose rm -v" and "docker rmi cfmetrics_grafana && docker rmi cfmetrics_heka"

Also just to make sure can you view the heka dashboard (localhost:4352) and verify that the decoders are correctly processing the incoming messages (process column large, process failure column small).
![screen shot 2016-10-24 at 1 08 14 pm](https://cloud.githubusercontent.com/assets/4573660/19658023/fc334ae0-99eb-11e6-9f44-a7f0c1766983.png)

**Comment by mjseid** [comment]
I'm assuming you've got this figured out.  If not feel free to re-open the ticket.  Thanks
